name = "tryveo4"
compatibility_date = "2024-08-26"
compatibility_flags = ["nodejs_compat"]

[env.production]
account_id = "your-account-id-here"
zone_id = "your-zone-id-here"

[env.development]
account_id = "your-account-id-here"

# Pages configuration for static assets and functions
pages_build_output_dir = ".next"

# Environment variables (these will be set in Cloudflare dashboard)
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://tryveo4.pages.dev"

# KV namespaces for caching if needed
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# R2 buckets for file storage
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "tryveo4-bucket"

# Define which routes should be handled by Workers
[functions."api/*"]
compatibility_date = "2024-08-26"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"